import React from 'react';
import HeroLayout from '../../../components/common/HeroLayout';
import DetailsLayout from '../../../components/common/DetailsLayout';
import FAQLayout from '../../../components/common/FAQLayout';
import ReviewsSection from '../../../components/common/ReviewsSection';

const CarbonFootprintCalculationConsulting = () => {
    return (
        <div className="bg-[#f8f9fa] min-h-screen relative font-sans">
            <div className="relative z-10 space-y-2 lg:space-y-4">
                <HeroLayout
                    heroTitleMain="Carbon Footprint Calculation"
                    heroTitleSuffix="Consulting"
                    heroDescription="Seeking carbon footprint calculation consulting services? Connect with VyomBiz to meet your ESG requirements and future-proof against climate risks."
                    stats={[
                        { count: "100K+", label: "Happy Customers" },
                        { count: "3500+", label: "Expert Advisors" },
                        { count: "50+", label: "Branch Offices" },
                        { count: "4.9", label: "Global Rating" }
                    ]}
                    formTitle="Get Free Expert Consultation"
                />

                <DetailsLayout
                    overview={{
                        title: "Carbon Footprint Calculation —",
                        highlightTitle: "An Overview",
                        description: [
                            "With carbon footprint calculation consulting, you can reduce emissions and achieve sustainability goals. By obtaining LEED Zero Carbon certification, entities will monitor and offset their carbon footprint through the application of carbon reduction and recovery practices.",
                            "The total amount of greenhouse gases, including carbon dioxide, methane, and nitrous oxide, is generated by transportation, chemical & garment manufacturing, mining, LPG use, and e-waste mismanagement.",
                            "With expert assistance, you can obtain calculations, analysis, credit reporting, and regulatory certification using cost-effective solutions."
                        ]
                    }}

                    advantages={{
                        title: "Emissions Scopes",
                        subtitle: "Categorizing Carbon Footprints",
                        list: [
                            {
                                title: "Scope 1",
                                desc: "Tracks direct and controlled sources such as factories, owned facilities, and company vehicle emissions."
                            },
                            {
                                title: "Scope 2",
                                desc: "Includes indirect emissions generated from the purchase of electricity, steam, cooling, and heat."
                            },
                            {
                                title: "Scope 3",
                                desc: "Emissions not directly controlled or owned by the entity, such as supply chain transport and e-waste."
                            }
                        ]
                    }}

                    process={{
                        title: "Our Consulting Process",
                        subtitle: "Measuring the Impact",
                        steps: [
                            {
                                step: "01",
                                title: "Define Boundaries & Goals",
                                desc: "Set clear goals concerning adherence to Indian regulations, classifying footprint based on scopes 1 to 3."
                            },
                            {
                                step: "02",
                                title: "Data Collection & Factors",
                                desc: "We help collect energy, operational, and transportation data, applying CPCB/IPCC emission factors."
                            },
                            {
                                step: "03",
                                title: "Calculation & Strategy",
                                desc: "Calculate the exact footprint footprints using LCA tools and align hotspots with your reduction targets."
                            }
                        ]
                    }}

                    features={{
                        title: "Benefits of Carbon Solutions",
                        subtitle: "Why manage your footprint?",
                        list: [
                            { title: "Cost-Effective", desc: "Identify energy mismanagement and implement measures that directly lower operational costs." },
                            { title: "Regulatory Compliance", desc: "Adhere to Indian and international reporting standard like SEBI BRSR and ESG guidelines." },
                            { title: "Brand Recognition", desc: "Companies proactively reducing emissions attract eco-conscious customers and establish brand loyalty." },
                            { title: "Investor Trust", desc: "ESG-focused investors overwhelmingly prefer businesses with transparent emission reporting." }
                        ]
                    }}

                    eligibility={{
                        title: "Who Needs This?",
                        subtitle: "Sectors with High Impact",
                        list: [
                            { title: "Manufacturing & Industrial", desc: "Chemical, metal, garment units, and power generation companies." },
                            { title: "Transportation & Logistics", desc: "Shipping, aviation, cargo networks, and bulk transport operators." },
                            { title: "Construction & Real Estate", desc: "Builders utilizing heavy materials and aiming for green certifications." },
                            { title: "Requirements", desc: "Must maintain records of energy, utility bills, waste generation, and supply chain data." }
                        ]
                    }}
                />

                <FAQLayout
                    title="Frequently Asked Questions"
                    subtitle="Carbon Calculation Queries"
                    faqs={[
                        {
                            question: "What is a Carbon Footprint?",
                            answer: "It is the total emissions generated from greenhouse gases directly related to human and business activities."
                        },
                        {
                            question: "What are the different scopes of carbon footprints?",
                            answer: "Scope 1 (direct controlled emissions), Scope 2 (indirect purchased energy), and Scope 3 (value chain indirect)."
                        },
                        {
                            question: "How does carbon footprinting help in corporate ESG?",
                            answer: "It ensures transparent reporting required by regulators (like BRSR in India) to demonstrate climate action to stakeholders."
                        },
                        {
                            question: "Can carbon calculations identify cost savings?",
                            answer: "Yes, by exposing energy inefficiencies and waste, businesses can directly save on utility expenses."
                        }
                    ]}
                />

                <ReviewsSection />
            </div>
        </div>
    );
};

export default CarbonFootprintCalculationConsulting;
