import React from 'react';
import docImage from '../../../assets/environmental-doc.png';
import HeroLayout from '../../../components/common/HeroLayout';
import DetailsLayout from '../../../components/common/DetailsLayout';
import FAQLayout from '../../../components/common/FAQLayout';
import ReviewsSection from '../../../components/common/ReviewsSection';

const EPRCredits = () => {
    return (
        <div className="bg-[#f8f9fa] min-h-screen relative font-sans">
            <div className="relative z-10 space-y-2 lg:space-y-4">
                <HeroLayout
                    heroTitleMain="EPR Credits Validation & Procurement"
                    heroTitleSuffix="— Best Prices"
                    heroDescription="Running short of EPR targets? Procure validated EPR credits from 300+ CPCB-authorized recyclers. Same-day transactions available for year-end compliance emergencies."
                    stats={[
                        { count: "43298 +", label: "Happy Clients" },
                        { count: "3500 +", label: "Expert Advisors" },
                        { count: "50 +", label: "Branch Offices" },
                        { count: "10k+", label: "Pin codes" }
                    ]}
                    formTitle="Get Free Expert Consultation"
                />

                <DetailsLayout
                    overview={{
                        title: "EPR Credits —",
                        highlightTitle: "An Overview",
                        description: [
                            "EPR credits are digital certificates earned by registered recyclers and plastic waste processors (PWPs) upon successfully recycling plastic packaging waste, e-waste, battery waste, or tyre waste. These credits are then made available for purchase on the centralized CPCB portal.",
                            "Producers, importers, and brand owners (PIBOs) who are unable to physically collect and recycle their entire EPR target can purchase these credits from authorized recyclers to meet their mandated Extended Producer Responsibility obligations.",
                            "The EPR credit trading system was introduced by CPCB under the Plastic Waste Management Rules (Amendment) 2022, and is now being rolled out for other waste categories including e-waste and battery waste, creating a structured market mechanism similar to carbon credits.",
                            "Each EPR credit represents 1 metric tonne of waste that has been collected and processed by an authorized recycler. The credit is generated on the CPCB portal after the recycler submits processed quantity data, which is validated and certified by the third-party auditor appointed by CPCB."
                        ],
                        whyIdealTitle: "Types of EPR Credits Available",
                        whyIdealList: [
                            { title: "Recycling Credits (Category-wise)", desc: "Credits for recycling Rigid, Flexible, Multi-layered, and Compostable plastic packaging." },
                            { title: "End-of-Life Disposal Credits", desc: "Credits for co-processing or scientifically disposing of plastic waste in cement kilns or waste-to-energy plants." },
                            { title: "Reuse Credits", desc: "Credits for reusing returnable plastic packaging that extends product life." },
                            { title: "E-Waste & Battery Credits", desc: "Credits generated by authorized e-waste dismantlers and battery recyclers for quantities processed." }
                        ]
                    }}

                    advantages={{
                        title: "Benefits of Procuring EPR Credits",
                        subtitle: "Why EPR credit procurement is the smart compliance strategy",
                        list: [
                            { title: "Target Fulfilment Without Infrastructure", desc: "Meet your EPR targets without setting up your own collection centers or recycling plants. Credits offer a cost-effective alternative for compliance." },
                            { title: "Cost-Effective Compliance", desc: "Buying bulk EPR credits from verified recyclers is often significantly cheaper than building and managing your own collection logistics." },
                            { title: "Complete Transparency & Traceability", desc: "All credit transactions occur on the government-managed CPCB portal with full digital traceability. Every credit is linked to actual tonnes of waste processed." },
                            { title: "Flexibility for Seasonal Businesses", desc: "Businesses with seasonal sales cycles or fluctuating production can use EPR credits to balance their annual compliance position." },
                            { title: "Audit-Proof Documentation", desc: "Credits purchased on the CPCB portal generate official digital certificates that are accepted as valid proof of EPR compliance during audits." },
                            { title: "Zero Penalty Risk", desc: "By ensuring 100% target fulfilment through a combination of physical collection and EPR credits, you eliminate all risk of CPCB penalties for target shortfall." }
                        ]
                    }}

                    eligibility={{
                        title: "Who Can Buy and Sell EPR Credits?",
                        subtitle: "Eligible entities in the EPR credit ecosystem",
                        list: [
                            { title: "Producers with Target Deficit", desc: "PIBOs who cannot physically collect their full EPR target can purchase credits to cover the shortfall." },
                            { title: "Small & Medium Businesses", desc: "SMEs with limited resources for collection infrastructure can rely entirely on credits for EPR compliance." },
                            { title: "Authorized Recyclers (Sellers)", desc: "CPCB-registered plastic waste recyclers generate and sell credits for every tonne of waste they process." },
                            { title: "Co-processors (Sellers)", desc: "Cement plants and waste-to-energy companies that co-process plastic waste can generate end-of-life credits for sale." },
                            { title: "Plastic Waste Processors (Sellers)", desc: "PWPs registered on the CPCB portal who process plastic waste into pellets, granules, or other recycled materials." }
                        ]
                    }}

                    documents={{
                        imageUrl: docImage,
                        title: "Documents for EPR Credit Procurement",
                        description: "Required documents to initiate EPR credit procurement process:",
                        list: [
                            "Valid EPR Registration Certificate",
                            "Target Deficit Calculation Report (current year EPR target vs. physical collection achieved)",
                            "Category-wise plastic distribution data (Rigid/Flexible/MLP/Compostable)",
                            "Annual sales and import data as filed with CPCB",
                            "Purchase Order for EPR Credits on CPCB portal",
                            "Bank details for credit transaction",
                            "Agreements with authorized recyclers (if direct procurement)",
                            "Previous year's annual return filing acknowledgment"
                        ]
                    }}

                    process={{
                        title: "EPR Credit Procurement Process",
                        subtitle: "Step-by-step guide to purchasing EPR credits on the CPCB portal",
                        steps: [
                            { step: "01", title: "Target Gap Analysis", desc: "Calculate your exact EPR credit requirement by comparing your annual target with the physical waste collected and recycled during the year." },
                            { step: "02", title: "Category-wise Credit Mapping", desc: "Identify the specific plastic category requirement — Rigid Plastic, Flexible Plastic, Multi-Layer Plastic, or Compostable packaging — based on your product mix." },
                            { step: "03", title: "Verified Recycler Identification", desc: "Shortlist CPCB-registered plastic waste processors with available credits in your required categories. We maintain a live database of available credits." },
                            { step: "04", title: "Price Negotiation", desc: "Negotiate credit pricing with the recycler. Prices vary by category, quantity, and market demand. Credits are typically priced between ₹8,000 to ₹25,000 per metric tonne." },
                            { step: "05", title: "Portal Transaction Execution", desc: "Execute the credit transfer on the CPCB/PWM online exchange portal. Both parties complete the transaction digitally with government-issued credit certificates." },
                            { step: "06", title: "Compliance Ledger Update & Filing", desc: "Attach the credit purchase certificates to your annual return and update your EPR compliance ledger on the portal to reflect 100% target achievement." }
                        ]
                    }}

                    postCompliance={{
                        title: "Key Regulations for EPR Credit Trading",
                        subtitle: "Regulatory framework governing EPR credit markets in India",
                        list: [
                            { title: "Plastic Waste Management Amendment, 2022", desc: "First introduced the EPR credit marketplace for plastic packaging waste under CPCB's centralized portal." },
                            { title: "EnvironmentProtection Act, 1986", desc: "The foundational legislation under which EPR rules and credit mechanisms derive their legal authority." },
                            { title: "Credit Validity Period", desc: "EPR credits for plastic waste are valid for 3 years from the date of generation. Credits must be purchased and applied before expiry." },
                            { title: "Carry Forward Not Allowed", desc: "Surplus physical collection beyond the annual target can be carried forward as credits to offset future year targets — excess credits purchased cannot be refunded." },
                            { title: "Third-Party Verification", desc: "CPCB appoints third-party auditors to verify the actual quantity of waste processed by recyclers before credits are generated on the portal." }
                        ]
                    }}

                    features={{
                        title: "Why Choose Corpbiz for EPR Credit Procurement?",
                        subtitle: "India's largest EPR credit marketplace partner",
                        list: [
                            { title: "Largest Recycler Network", desc: "Access to 300+ CPCB-registered recyclers across all states with real-time credit availability data." },
                            { title: "Category-wise Credit Availability", desc: "We source credits specifically matching your Rigid, Flexible, MLP, or Compostable plastic requirements." },
                            { title: "Best Price Guarantee", desc: "Our bulk procurement partnerships with recyclers guarantee the best market rates for EPR credits." },
                            { title: "End-to-End Portal Transaction Support", desc: "Full support for completing the credit transaction on the CPCB PWM portal, from login to digital credit certificate generation." },
                            { title: "Zero Penalty Track Record", desc: "100% of our clients who procured credits through Corpbiz have achieved compliance without incurring any CPCB penalties." },
                            { title: "Same-Day Transaction Capability", desc: "For urgent compliance deadlines, we can execute credit nominations within 24 hours through our pre-verified recycler relationships." }
                        ]
                    }}
                />

                <FAQLayout
                    title="Frequently Asked Questions"
                    subtitle="Get answers to the most common questions about this service."
                    faqs={[
          {
                    "question": "What are EPR credits?",
                    "answer": "EPR credits are digital certificates generated by CPCB-registered recyclers for every metric tonne of waste they collect and process. PIBOs who cannot physically meet their EPR targets can purchase these credits on the centralized CPCB portal to achieve compliance."
          },
          {
                    "question": "How much do EPR credits cost in India?",
                    "answer": "EPR credit prices vary by waste category and market conditions. Plastic waste credits typically range from ₹8,000 to ₹30,000 per metric tonne. E-waste and battery credits are priced differently. Corpbiz's network ensures the best market rates for bulk purchases."
          },
          {
                    "question": "How long are EPR credits valid?",
                    "answer": "Plastic waste EPR credits are valid for 3 years from the date of generation on the CPCB portal. Credits must be purchased and applied to the PIBO's compliance ledger before this validity period expires."
          },
          {
                    "question": "Can EPR credits be carried forward to the next year?",
                    "answer": "Surplus physical collection beyond the annual target can be converted into credits carried forward to the next year. However, purchased EPR credits that exceed the current year's requirement generally cannot be refunded."
          },
          {
                    "question": "Who generates EPR credits?",
                    "answer": "EPR credits are generated by CPCB-registered plastic waste processors (PWPs), e-waste recyclers/dismantlers, battery recyclers, and tyre recyclers. Credits are generated on the CPCB portal after submitting processed quantity data, verified by a third-party auditor."
          },
          {
                    "question": "Are EPR credits legally accepted proof of compliance?",
                    "answer": "Yes. EPR credit purchase certificates generated on the official CPCB portal are the legally accepted proof of compliance. These certificates are submitted with annual returns and accepted during CPCB audits."
          },
          {
                    "question": "What is the process to purchase EPR credits?",
                    "answer": "The PIBO logs into the CPCB portal, creates a purchase request specifying the required category and quantity, selects a verified recycler with available credits, completes the transaction, and receives a digital credit certificate. Corpbiz manages this entire process for clients."
          }
]}
                />
                <ReviewsSection />
            </div>
        </div>
    );
};

export default EPRCredits;
